spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 62686a336513fd
    password: 7ceb8adfde8da2
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085
        specific:
          avro:
            reader: true
server:
  port: 8083


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.observations.key-values.application: ${spring.application.name}

management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

loki.url: http://localhost:3100/loki/api/v1/push


---
spring.config.activate.on-profile: docker

server.port: 8080

spring.kafka.bootstrap-servers: kafka:9092

spring.kafka.producer.properties.schema.registry.url: http://schema-registry:8085

management.zipkin.tracing.endpoint: http://tempo:9411/api/v2/spans

loki.url: http://loki:3100/loki/api/v1/push

