---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo:9411"
  PRODUCT_SERVICE_URL: "http://product-service:8084"
  ORDER_SERVICE_URL: "http://order-service:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service:8082"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka:29092"
